# Use the official NGINX base image
FROM nginx:latest

# Set maintainer information
LABEL maintainer="Zhanna Kutuzova <your.email@example.com>"

# Create a simple HTML page
RUN echo '<html><body><h1>Hello from Zhanna Kutuzova - Cloud Engineer!</h1></body></html>' > /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80

# Start NGINX server
CMD ["nginx", "-g", "daemon off;"]
